Better movement system calculation
ThunbergOlle/virtcon2 pull request #6
Opened 2023-03-05 12:20 UTC by Zilonis123

2023-03-05 20:22 UTC, ThunbergOlle requested changes
Overall LGTM, just one small comment, please fix b4 merging! :D

2023-03-05 20:22 UTC, ThunbergOlle commented on src/gameObjects/player/Player.ts
> +      else console.log(`The inventory can't hold ${item.amount} items.`)
This is already checked in the above statement, we check if the items we want to add will make our inventory too full,

Please remove this 😄

2023-03-06 12:15 UTC, Zilonis123 commented on src/gameObjects/player/Player.ts
> +      else console.log(`The inventory can't hold ${item.amount} items.`)
Removed it :)

2023-03-06 13:14 UTC, OlleThunbergDevoteam approved these changes

2023-03-06 17:02 UTC, ThunbergOlle approved these changes

2023-03-06 17:04 UTC, merged